name: Build Linux Project

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check build folder cache
        uses: actions/cache@v2
        with:
          path: build/
          key: ${{ runner.os }}-cmake-${{ github.sha }}
          restore-keys: |
            ${{ runner.OS }}-cmake-

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Install box2d Project
        run: |
          sudo apt-get install xorg-dev libglu1-mesa-dev
          cd Libraries/Box2D
          mkdir build
          cd build
          cmake -DBOX2D_BUILD_EXAMPLES=OFF -DBOX2D_BUILD_DOCS=ON ..
          cmake --build .
          sudo make install
          cd ../../../

      - name: Build Project
        run: |
          cmake -S . -B ./build
          
      - name: Build Executable
        run: |
          cd build
          make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: NightByte-Linux
          path: |
            build/bin
