name: Build Project

on:
  push:
    branches: [develop, feature/doxygen]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt install gcc make cmake git

      - name: Checkout submodules
        shell: bash
        run: |
          # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
          # git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Build Project
        run: |
          cmake -S . -B ./build

      - name: Build Executable
        run: |
          cd build
          make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            build/bin
