name: Build Project

on:
  push:
    branches: [develop, feature/doxygen]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt install gcc make cmake git

      - name: Pull Submodules
        uses: textbook/git-checkout-submodule-action@master
        with:
          remote: true

      - name: Build Project
        run: |
          cmake -S . -B ./build

      - name: Build Executable
        run: |
          cd build
          make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            build/bin
