name: Build Project

on:
  push:
    branches: [develop, feature/doxygen]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt install gcc make cmake git

      - name: Pull Submodules
        run: |
          git submodule update --init --recursive --remote

      - name: Build Project
        run: |
          cmake -S . -B ./build

      - name: Build Executable
        run: |
          cd build
          make
        with:
          name: binaries
          path: |
            build/bin
