name: Build Windows Project

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build-win:
    runs-on: windows-latest

    steps:

      -uses: uses: actions/checkout@v2
      
      - name: Check build folder cache
        uses: actions/cache@v2
        with:
          path: build/
          key: ${{ runner.os }}-cmake-${{ github.sha }}
          restore-keys: |
            ${{ runner.OS }}-cmake-

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Build Project
        run: |
          cmake -S . -B ./build -G "MinGW Makefiles"

      - name: Build Executable
        run: |
          cd build
          make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: NightByte-Windows
          path: |
            build/bin
