name: Build Windows Project

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey
          key: ${{ runner.os }}-chocolatey-${{ matrix.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-chocolatey-${{ matrix.os }}-
            ${{ runner.os }}-chocolatey-

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest        ⟸ THIS IS THE ONE LINER YOU NEED

      - name: Install Dependencies
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install mingw make git

      - name: Checkout submodules
        shell: bash
        run: |
          # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
          # git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - uses: actions/cache@v2
        with:
          path: build/
          key: ${{ runner.os }}-cmake-${{ matrix.os }}-${{ github.sha }}

      - name: Build Project
        run: |
          cmake -S . -B ./build -G "MinGW Makefiles"

      - name: Build Executable
        run: |
          cd build
          make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: NightByte-Windows
          path: |
            build/bin
